# Generated by Django 3.2.3 on 2021-08-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='tipstext',
            new_name='tipstitle',
        ),
        migrations.RemoveField(
            model_name='tips',
            name='username',
        ),
        migrations.AddField(
            model_name='tips',
            name='tips_dis',
            field=models.TextField(default=''),
        ),
    ]
